spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 192.168.121.36:9092    
    topic:
      new-post: k8s_dev_topic_new_post_for_
      delete-post: k8s_dev_topic_delete_post_for_
      email-queue: k8s_dev_topic_email_queue_
      notification-queue: k8s_dev_topic_notification_queue_
      sms-queue: k8s_dev_topic_sms_queue_
      new-reaction: k8s_dev_topic_new_reaction_for_
      update-reaction: k8s_dev_topic_update_reaction_for_
      delete-reaction: k8s_dev_topic_delete_reaction_for_
      new-comment: k8s_dev_topic_new_comment_for_
      delete-comment: k8s_dev_topic_delete_comment_for_
      new-rating: k8s_dev_topic_new_rating_for_
      update-rating: k8s_dev_topic_update_rating_for_
      delete-rating: k8s_dev_topic_delete_rating_for_
      new-like: k8s_dev_topic_new_like_for_
      delete-like: k8s_dev_topic_delete_like_for_
      new-share: k8s_dev_topic_new_share_for_
      delete-share: k8s_dev_topic_delete_share_for_
      update-user-profile: k8s_dev_topic_update_user_profile_for_ 
      delete-user-service: k8s_dev_topic_delete_user_service
      active-user-service: k8s_dev_topic_active_user_service
      deactive-user-service: k8s_dev_topic_deactive_user_service
      block-user-service: k8s_dev_topic_block_user_service
      count-product: k8s_dev_topic_count_product
      catalog-product-sys: k8s_dev_topic_catalog_product_sys
      catalog-update-quantity: k8s_dev_topic_catalog_update_quantity
      catalog-update: k8s_dev_topic_catalog_update
      catalog-shop-update: k8s_dev_topic_catalog_shop_update
      update-shop-address: k8s_dev_topic_update_shop_address
      update-rating-product: k8s_dev_topic_update_rating_product
      shopping-trends: k8s_dev_topic_shopping_trend
      new-page: k8s_dev_topic_new_page_for_
      scheduling-rating: k8s_dev_topic_scheduling_rating_for_
      data-change-for-neo4j: k8s_dev_topic_data_for_neo4j
      new-follower: k8s_dev_topic_new_follower_for_
      delete-follower: k8s_dev_topic_delete_follower_for_
      food-type-update-quantity: k8s_dev_topic_food_type_update_quantity
      count-object: k8s_dev_topic_count_for_
      count-review-restaurant: k8s_dev_topic_count_review_restaurant
      change-name-catalog: k8s_dev_topic_change_name_catalog_for_
      delete-product: k8s_dev_topic_delete_product_for_
      delete-food: k8s_dev_topic_delete_food_for_
      update-food-type: k8s_dev_topic_update_food_type_for_
      create-webp-topic: k8s_dev_topic_storage_create_webp_server
      create-webm-topic: k8s_dev_topic_storage_create_webm_server
      new-voucher: k8s_dev_topic_new_voucher_for_
      delete-voucher: k8s_dev_topic_delete_voucher_for_
      update-restaurant: k8s_dev_topic_update_restaurant_for_
  ws:
    destination:
      ecommerce-food: public_cart_food
      ecommerce-product: public_cart_product
  session:
    store-type: redis
    redis:
      namespace: dev
  data:
    redis:
      database: 1
      port: 6379
      timeout: 30000
      host: 192.168.121.32
      username: default
      password: 12345678x@X
  cache:
    type: redis
    redis:
      time-to-live: '45000'
      cache-null-values: 'true'
  jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                id:
                    new_generator_mappings: false
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    username: cassandra
    password: 12345678x@X
    local-datacenter: dc1
    request:
      timeout: 10s
    port: '9042'
    connection:
      init-query-timeout: 10s
      connect-timeout: 10s
    contact-points: 192.168.121.29
    
  neo4j:
    uri: neo4j://192.168.121.37:7687
    authentication:
      username: neo4j
      password: 12345678x@X_neo4j

server:
  http2:
    enabled: true
app:
  greeting: Hello from config file on github at folder dev
  gateway:
    domain-name: https://api-dev-soctrip.tma-swerp.com
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
logging:        
  file:
    name: application.log
  level:
    root: INFO
    org.springframework: INFO

es:
  hostname: 192.168.121.101
  port: 9200
  username: elastic
  password: 12345678x@X
